// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TosProject.Model;

namespace TosProject.Migrations
{
    [DbContext(typeof(DbEntites))]
    [Migration("20200912202002_Dt1")]
    partial class Dt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TosProject.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "0791814332",
                            Email = "infor@walden.co.za",
                            EmployeeNo = "EMP-0124",
                            Firstname = "Walden",
                            Lastname = "Schmidt",
                            Website = "www.walden.co.za"
                        },
                        new
                        {
                            Id = 2,
                            Contact = "0718798898",
                            Email = "infor@roselee.co.za",
                            EmployeeNo = "EMP-0088",
                            Firstname = "RoseLee",
                            Lastname = "Cheryl",
                            Website = "www.roselee.co.za"
                        },
                        new
                        {
                            Id = 3,
                            Contact = "0670058981",
                            Email = "infor@evans.co.za",
                            EmployeeNo = "EMP-0136",
                            Firstname = "Evans",
                            Lastname = "Mazi",
                            Website = "www.evans.co.za"
                        },
                        new
                        {
                            Id = 4,
                            Contact = "0791814332",
                            Email = "infor@kagiso.co.za",
                            EmployeeNo = "EMP-0461",
                            Firstname = "Kagiso",
                            Lastname = "Mandla",
                            Website = "www.kagiso.co.za"
                        },
                        new
                        {
                            Id = 5,
                            Contact = "0791814332",
                            Email = "infor@caroline.co.za",
                            EmployeeNo = "EMP-0661",
                            Firstname = "Caroline",
                            Lastname = "Smith",
                            Website = "www.caroline.co.za"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
